### ISSUE TITLE
Data Tidak Update

### ISSUE THREAD

**Issue by mdestafadilah** [bagoesz21/php-nik-parser#1]
Halo, data tidak update ya?

**Comment by bagoesz21** [comment]
Hello,
iya, data wilayah diambil dari sini gan ...

[https://github.com/mul14/nik_parser.ts](https://github.com/mul14/nik_parser.ts)

**Comment by mdestafadilah** [comment]
waduh, saya pake lib itu juga muncul error... 

![OBJEK-KECAMATAN](https://user-images.githubusercontent.com/5575882/200245518-fac82359-ebbc-46a0-af57-999a5e30b17c.png)

bingung mau bikin issue, sepertinya di disable

**Comment by bagoesz21** [comment]
di fork saja, terus pull requests ..

**Comment by mdestafadilah** [comment]
> di fork saja, terus pull requests ..

yaps, otw ini juga, masih test local, thanks suggestion nya mas.
